# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6313d1b02254e0f025a8f515d279b883f68293e1e1c9e1307d94a5e1c90eb88e6f7197913ebcde16a3ad8378c0d24ce31701b44e178e61f7f0964919d1337153

test:
  secret_key_base: 55047070dd389546ea0fdcc1ab7f8e9a7292b7fa42625236b6e438ca686e5826b9586b5eb08149d6d45d44856d28ba8f25a359b05ed553927c043158082b5982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
